rfc-vote/rfc-vote

database/factories/RfcFactory.php, database/migrations/2023_07_31_132007_create_rfcs_table.php, resources/views/home.blade.php, resources/views/rfc.blade.php
This pull request adds a short RFC description as mentioned in #8 to the database migration, to the factory and to the templates. No frontend beauty of course.
=> #8 Short RFC description

app/Http/Livewire/ArgumentForm.php, app/Http/Livewire/ArgumentList.php, app/Http/Livewire/Events.php, app/Http/Livewire/VoteBar.php, app/Models/User.php, resources/views/livewire/argument-list.blade.php, resources/views/livewire/vote-bar.blade.php
hi Brent...
I was able to implement the ability for users to undo their votes, which also decrements the reputation they gained.
=> added the ability to undo a vote

app/Models/User.php, package-lock.json, resources/views/components/user-name.blade.php, resources/views/components/user-popup.blade.php, resources/views/livewire/argument-list.blade.php
this PR adds the popup component https://github.com/brendt/rfc-vote/issues/23
Note: I've replaced the null value in the getAvatarUrl() method with a static image link to ensure the image is displaying properly. We can consider giving the avatar column a default value later on.
=> adding the popup component

resources/views/livewire/argument-list.blade.php
=> Fix markdown escaping

resources/views/layouts/base.blade.php
=> fix: make page expand to full height

app/Http/Controllers/ForgotPassword.php, config/services.php, resources/views/auth/forgot-password.blade.php, resources/views/auth/reset-password.blade.php, resources/views/components/authentication-card.blade.php, resources/views/components/button.blade.php, resources/views/login.blade.php, routes/web.php
this pr is related to https://github.com/brendt/rfc-vote/issues/26
I've utilized Jetstream's existing offerings in this term by simply connecting its components instead of building a custom flow from scratch.
=> password reset flow

tests/Feature/RfcTest.php, tests/TestCase.php
this pr adds more test cases related to the RFC CURD operations!
=> adding more test cases

resources/views/register.blade.php
Like the `login` inputs, it is better that the `required` attribute added to `register` view inputs. #1
=> Add `required` attribute to `register` inputs

app/Actions/DeleteArgument.php, app/Http/Livewire/ArgumentList.php, app/Models/User.php, app/Policies/ArgumentPolicy.php, resources/views/components/argument-card.blade.php, tests/Feature/ArgumentTest.php
Using ‍‍‍‍`Argument Policy` seems to make our code cleaner.
=> Add `ArgumentPolicy`

README.md, docker-compose.yml
I added redis to docker-compose.yml and tested to make sure that horizon works locally as well.
=> Add redis service and make sure horizon works locally as well.

resources/views/components/argument-card/button.blade.php, resources/views/components/argument-card/card.blade.php
Not really sure about the solution.
Closes #110
=> Add anchor link to arguments

app/Http/Livewire/ArgumentList.php, database/factories/UserFactory.php, resources/views/components/argument-card/card.blade.php, routes/web.php
this PR fixes a bug when the user tries to edit his argument and clear the body and save it empty
=> fixing a bug

app/Http/Controllers/HomeController.php, app/Models/Rfc.php, app/Models/User.php, resources/views/home.blade.php
This PR related to this [issue](https://github.com/brendt/rfc-vote/issues/108)
=> show an indicator on the RFCs home page to show if the logged-in user has voted

resources/views/layouts/base.blade.php
I've replaced the vanillajs code with alpinejs attributes to manage the "toTop" button state,
I'd like to extend my gratitude to @SerhiiCho  for his recent PRs, as they have significantly contributed to my understanding of alpinejs.
=> Replace vanillajs with Alpinejs to handle the state of the 'To Top' button

app/Http/Controllers/SocialiteCallbackController.php
Required to prevent session fixation: https://laravel.com/docs/10.x/session#regenerating-the-session-id
=> Regenerating The Session ID

resources/views/components/navbar/link.blade.php, resources/views/components/navbar/mobile-menu-trigger.blade.php, resources/views/components/profile/user-menu/menu.blade.php, resources/views/layouts/base.blade.php
Added proper mobile navigation menu with a little bit of Alpine.JS
Also added "Open RFCs" and "Register" links to the navigation bar. So now we have 4 links for guests like this:
=> Added Mobile Menu Navigation

app/Http/Controllers/RfcDetailController.php, resources/views/components/argument-card/card-footer.blade.php, resources/views/rfc.blade.php
this PR takes care of this [issue](https://github.com/brendt/rfc-vote/iss
ues/150)
and add this [feature](https://github.com/brendt/rfc-vote/issues/54)
=> show additional RFCs to the user, and take care of the new badge on the argument of the day.

resources/views/livewire/argument-list.blade.php
From this:
```php
@php
if ($userArgument?->is($argument)) {
continue;
}
@endphp
```
to this:
```php
@if ($userArgument?->is($argument))
@continue
@endif
```
=> Refactored if statement in blade

resources/views/components/message-card/card.blade.php, resources/views/components/message-card/option.blade.php, resources/views/components/message-card/options.blade.php, resources/views/livewire/message-list.blade.php
Moved buttons to a popup menu simlilar to what we have on argument cards:
Related #176
=> Argument comments card redesign

app/Console/Commands/RfcSyncCommand.php
Super simple description update for listing commands in app
=> Update RfcSyncCommand description

resources/views/components/markdown-editor.blade.php
As agreed, I removed the status line from the editor.
=> Remove markdown editor statistics

app/Models/VoteType.php, database/seeders/DatabaseSeeder.php
so, I'm really bad at reading code,
this perhaps add just a bit more readability=)
=> style: added opposite static method to VoteType

app/Models/UserFlair.php, resources/views/components/profile/flair.blade.php
=> Add description for user flair

resources/css/_variables.css, resources/views/about.blade.php, resources/views/components/argument-card/card-footer.blade.php, resources/views/components/email-optin-banner.blade.php, resources/views/components/form/input.blade.php, resources/views/components/form/textarea.blade.php, resources/views/components/message-card/options.blade.php, resources/views/components/navbar/link.blade.php, resources/views/components/success-message.blade.php, resources/views/home.blade.php, resources/views/layouts/base.blade.php, resources/views/rfc-admin.blade.php, resources/views/rfc.blade.php, tailwind.config.js
I know you like dark themes @brendt, here, I fixed some of the leftovers that needed to be fixed on dark theme. Here are the screenshots of some of them:
=> 🌗 Dark theme style fixes

.github/dependabot.yml, app/Models/User.php
Added a dependabot.yml configuration file to enable automatic dependency updates for npm and composer packages. This will ensure the application stays secure and up-to-date without manual intervention.
=> Add dependabot configuration file

resources/css/app.css, resources/views/about.blade.php, resources/views/components/argument-card/card.blade.php, resources/views/components/rfc/tutorial.blade.php, resources/views/home.blade.php, resources/views/rfc.blade.php
This pull request corrects the text color in the argument body for anchor tags and written code
=> the argument body in dark mode

app/Http/Requests/RfcRequest.php, database/factories/RfcFactory.php, database/migrations/2023_08_31_073243_add_externals_url_to_rfcs.php, resources/views/rfc-form.blade.php, resources/views/rfc.blade.php
Basic implementation of adding `externals_url` to Rfcs through admin. Feel free to adjust
=> Added optional `externals_url` to `Rfc`

resources/views/components/argument-card/share-links.blade.php
This is fix of https://github.com/brendt/rfc-vote/issues/243
=> Fix Linkedin share issue

resources/views/components/argument-card/share-links.blade.php
This PR related to this [issue](https://github.com/brendt/rfc-vote/issues/246)
=> Link the argument to the social links

contributors.json, database/seeders/DatabaseSeeder.php
This PR adds fake argument votes.
Caveats
- There is no checking to of users maximum vote count per RFC
- The users reputation is not updated
=> Agument Vote Faking

resources/css/app.css, resources/views/components/rfc/tutorial.blade.php
this PR fixes the markdown styling on the RFC page
=> fix the markdown

resources/views/components/card-link.blade.php, resources/views/home.blade.php, resources/views/rfc.blade.php
Added a link "Read more" to RFC cards instead of using the whole card as a link.
closes #242
=> Home arguments link

app/Http/Controllers/ProfileController.php, database/factories/VerificationRequestFactory.php, tests/Feature/CreateVerificationRequestTest.php
This pull request includes additional tests for the verification request flow.
=> more test cases

app/Policies/RfcPolicy.php, resources/views/vendor/pagination/tailwind.blade.php
Added styles to pagination links, including dark theme:
=> Added styles to pagination links

app/Http/Livewire/ArgumentList.php, resources/css/app.css, resources/views/components/about/link.blade.php, resources/views/components/argument-card/card.blade.php, resources/views/components/card-link.blade.php, resources/views/components/rfc/tutorial.blade.php, resources/views/home.blade.php, resources/views/rfc.blade.php, tailwind.config.js
This PR closes #269 and closes #280 
It also fixes the style of the recommended RFCs as they were not sharing the width evenly.
before:
after:
=> fix two bugs

resources/views/components/navbar/dark-mode-button.blade.php, resources/views/components/navbar/navbar.blade.php, resources/views/layouts/base.blade.php
1. Simplified `base.blade.php` template file by extracting the navigation bar into a separate component `navbar/navbar.blade.php`
2. Simplified `navbar/navbar.blade.php` by extracting the dark mode button into a separate component `navbar/dark-mode-button.blade.php`
I've noticed that a couple of styling issues appeared recently with the navigation bar, so I wanted to fix them but noticed that the navigation bar is growing and deserves a separate component before I make any fixes.
=> 🎨 Moved the navigation bar to Blade component

LICENSE.md
I don't know whether you wanted to add a license or not, I'm proposing this one, it's just a standard license provided by GitHub, but you can decline this PR and write your own. I just thought it would be nice to have it so that it's open-sourced not just by words, but documented as well.
> Please, check your first and last name in the license
=> 📚 Added LICENSE file

resources/views/livewire/user-list.blade.php
Nothing special in this PR, there is a [user-list.blade.php](https://github.com/brendt/rfc-vote/blob/451fc7285ee7fb5da8b625e927c63de75dec2aca/resources/views/livewire/user-list.blade.php) that needs to be formatted a bit
=> Formatted user-list.blade.php file

resources/views/home.blade.php
=> Align card content

resources/views/components/buttons/to-top.blade.php, resources/views/layouts/base.blade.php
Moved “to top” button into a separate blade component to `components/buttons/` directory
=> Moved "to top" button into a separate blade component

resources/views/home.blade.php
Removed translation functions from `home.blade.php` since we are not gonna use them
=> Removed translation functions from home blade file

resources/views/auth/confirm-password.blade.php, resources/views/auth/forgot-password.blade.php, resources/views/auth/login.blade.php, resources/views/auth/register.blade.php, resources/views/auth/reset-password.blade.php, resources/views/auth/two-factor-challenge.blade.php, resources/views/auth/verify-email.blade.php
Cleaned up and formatted blade files in auth directory
=> Cleaned up and formatted blade files in auth directory

resources/views/layouts/base.blade.php
closes #340
Fixed broken highlight on code examples bug
=> Fixed broken code highlight

resources/views/components/argument-card/card-footer.blade.php, resources/views/rfc.blade.php
Removed __() functions from 2 blade files since we are not going to use translations
=> Removed translation functions from 2 blade files

resources/views/rfc-meta-base.blade.php
Formatted `rfc-meta-base.blade.php` file
=> Formatted rfc-meta-base.blade.php file

app/Http/Controllers/RfcDetailController.php, resources/views/components/buttons/to-top.blade.php, resources/views/rfc.blade.php
Closes #392
Fixed styles for another RFCs section on the bottom of the RFC page
Also, small fix of this z-index CSS issue:
=> Another rfcs fix

app/Http/Controllers/RfcDetailController.php, app/Http/Livewire/ArgumentList.php, app/Http/Middleware/AdminMiddleware.php, database/factories/UserFactory.php, resources/views/components/argument-card/card-footer.blade.php, resources/views/components/argument-card/card.blade.php, resources/views/home.blade.php, resources/views/livewire/argument-list.blade.php, resources/views/public-profile.blade.php, resources/views/rfc.blade.php, tests/Browser/Pages/LoginPage.php, tests/Browser/Pages/RegisterPage.php, tests/TestCase.php
Undo the https://github.com/brendt/rfc-vote/pull/404 pull request
=> Undo two column layout

resources/views/components/navbar/dark-mode-button.blade.php
Change tooltip content on theme switcher from `Switch to light theme` to `Dark theme`, etc
=> Change tooltips content on theme switcher

app/Http/Controllers/DisableEmailOptinController.php, app/Http/Controllers/EnableEmailOptinController.php
Change the notification message from `Your email preferences were updated!` to `Your email preferences were updated! You can change them at any time in your Settings.` for better clarity
=> Update notification messages

resources/css/_variables.css, resources/views/components/email-optin-banner.blade.php, resources/views/layouts/base.blade.php, tailwind.config.js, tests/Browser/RegistrationTest.php
Change opt-in notification message content:
Also change styles for flash messages in `base.blade.php` by reusing existing blade component for flash messages:
=> Improve notification styles

app/Http/Controllers/EnableEmailOptinController.php
Remove new line in a string to fix Dusk test failing
=> Fix Dusk test
